// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfr8n9RZZDjvZ-b8QF3kKkILHTvRQLbo',
    appId: '1:861109679016:web:53d3304f18ac5817a5a39d',
    messagingSenderId: '861109679016',
    projectId: 'littafy-7130d',
    authDomain: 'littafy-7130d.firebaseapp.com',
    storageBucket: 'littafy-7130d.appspot.com',
    measurementId: 'G-HXDJPNSKY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcwqhqDxcmHDfXDi7WyKQgBdc9iDDL32k',
    appId: '1:861109679016:android:bf0f974de0988fa9a5a39d',
    messagingSenderId: '861109679016',
    projectId: 'littafy-7130d',
    storageBucket: 'littafy-7130d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7A5l5bLI_7TVNLgttWr2oPRuKoRLbnlo',
    appId: '1:861109679016:ios:863d66fdeebc5349a5a39d',
    messagingSenderId: '861109679016',
    projectId: 'littafy-7130d',
    storageBucket: 'littafy-7130d.appspot.com',
    iosBundleId: 'com.littafy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7A5l5bLI_7TVNLgttWr2oPRuKoRLbnlo',
    appId: '1:861109679016:ios:80973ba47bccebf8a5a39d',
    messagingSenderId: '861109679016',
    projectId: 'littafy-7130d',
    storageBucket: 'littafy-7130d.appspot.com',
    iosBundleId: 'com.littafy.app.RunnerTests',
  );
}
